# site.yml
---
# 1. Initialize Proxmox Host
- import_playbook: playbooks/pve-init.yml

# 2. Configure ZFS Storage Layout (Creates datasets)
- import_playbook: playbooks/zfs-layout.yml

# 3. Register Proxmox Storage (Registers zfs-pools with PVE) <--- NEW STEP
- import_playbook: playbooks/pve-storage.yml

# 4. Configure Network Interfaces (PVE Bridges)
- import_playbook: playbooks/pve-networking.yml

# 5. Provision and Configure AdGuard LXC
- import_playbook: playbooks/lxc-adguard.yml
