all:
  hosts:
    gamecube:
      ansible_host: 192.168.0.20
      ansible_connection: local
      ansible_user: root

    link-cable:
      ansible_host: 192.168.0.30

    randnet:
      ansible_host: 192.168.0.32

    warp-zone:
      ansible_host: 192.168.0.34

    file-select:
      ansible_host: 192.168.0.36

netbird:
  hosts:
    randnet: {}
