# inventories/prod/hosts.yml
all:
  children:
    # ----------------------------------------------------
    # PROXMOX HOST
    # ----------------------------------------------------
    proxmox_host:
      hosts:
        gamecube:
          ansible_host: 192.168.0.20
          ansible_connection: local
          ansible_user: root

    # ----------------------------------------------------
    # LXC CONTAINERS
    # ----------------------------------------------------
    lxc_containers:
      hosts:
        # We use the legacy name 'link-cable' to match existing ZFS datasets
        link-cable:
          ansible_host: 192.168.0.30

    # ----------------------------------------------------
    # VM GUESTS
    # ----------------------------------------------------
    vm_guests:
      hosts:
        pass
