# inventories/prod/hosts.yml
all:
  children:
    # ----------------------------------------------------
    # PROXMOX HOST
    # ----------------------------------------------------
    proxmox_host:
      hosts:
        gamecube:
          ansible_host: 192.168.0.20
          ansible_connection: local
          ansible_user: root

    # ----------------------------------------------------
    # LXC CONTAINERS
    # ----------------------------------------------------
    lxc_containers:
      vars:
        ansible_user: root
        ansible_ssh_private_key_file: /root/.ssh/id_ed25519_ansible

      hosts:
        link-cable:
          ansible_host: 192.168.0.30

    # ----------------------------------------------------
    # VM GUESTS
    # ----------------------------------------------------
    vm_guests:
      hosts:
        pass
